// Product data
const products = [
    {
        id: 1,
        name: "Classic Oxford Shoes",
        category: "men",
        price: 2999,
        originalPrice: 3999,
        discount: 25,
        rating: 4.5,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/fb2e4b9b-bdc4-4d18-acd8-ad34bd657555/NIKE+V2K+RUN.png" alt="Classic Oxford" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Best Seller",
        description: "Premium leather Oxford shoes perfect for formal occasions."
    },
    {
        id: 2,
        name: "Elegant Heels",
        category: "women",
        price: 2499,
        originalPrice: 3499,
        discount: 30,
        rating: 4.3,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/2fb6ff59-aca1-4f1f-a836-0888d4f119a6/W+NIKE+V2K+RUN.png" alt="Elegant Heels" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "New",
        description: "Stylish heels designed for comfort and elegance."
    },
    {
        id: 3,
        name: "Running Sneakers",
        category: "sports",
        price: 3999,
        originalPrice: 4999,
        discount: 20,
        rating: 4.7,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/eb311648-a679-4987-83b7-4f85ce9ce876/NIKE+V2K+RUN.png" alt="Running Sneakers" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Popular",
        description: "High-performance running shoes with advanced cushioning."
    },
    {
        id: 4,
        name: "Kids School Shoes",
        category: "kids",
        price: 1299,
        originalPrice: 1799,
        discount: 28,
        rating: 4.4,
        image: '<img src="https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/d14af056-76ba-44a2-9e84-6c64f47778cf/custom-v2k-run-shoes-by-you.png" alt="Kids School Shoes" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Sale",
        description: "Durable and comfortable school shoes for children."
    },
    {
        id: 5,
        name: "Formal Loafers",
        category: "men",
        price: 2799,
        originalPrice: 3599,
        discount: 22,
        rating: 4.2,
        image: '<img src="https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/07257ea2-26f9-4a51-b5f2-f441c3671970/custom-v2k-run-shoes-by-you.png" alt="Formal Loafers" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Limited",
        description: "Classic loafers made with genuine leather."
    },
    {
        id: 6,
        name: "Casual Sandals",
        category: "women",
        price: 1599,
        originalPrice: 2299,
        discount: 30,
        rating: 4.1,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/82294235-c384-4e08-bb65-897aedd00890/AIR+ZOOM+PEGASUS+41JI.png" alt="Casual Sandals" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Summer",
        description: "Comfortable sandals perfect for casual wear."
    },
    {
        id: 7,
        name: "Basketball Shoes",
        category: "sports",
        price: 4999,
        originalPrice: 6999,
        discount: 29,
        rating: 4.8,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0dceb03f-c1e8-4f17-abce-0c2aac15f491/AIR+ZOOM+PEGASUS+41.png" alt="Basketball Shoes" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Pro",
        description: "Professional basketball shoes with superior grip."
    },
    {
        id: 8,
        name: "Kids Sneakers",
        category: "kids",
        price: 1699,
        originalPrice: 2299,
        discount: 26,
        rating: 4.6,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/48f95923-b211-4296-ab5d-3e688df29762/NIKE+P-6000+PRM.png" alt="Kids Sneakers" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Colorful",
        description: "Fun and colorful sneakers for active kids."
    },
    {
        id: 9,
        name: "Premium Derby Shoes",
        category: "men",
        price: 3499,
        originalPrice: 4499,
        discount: 22,
        rating: 4.6,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/97565f94-62bc-4409-b529-f7f9e0a44a7b/PEGASUS+PLUS.png" alt="Premium Derby" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Premium",
        description: "Premium Derby shoes for special occasions."
    },
    {
        id: 10,
        name: "Stiletto Heels",
        category: "women",
        price: 2899,
        originalPrice: 3899,
        discount: 26,
        rating: 4.4,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9c7ff379-a69f-4dc5-a979-a6de2816d2a2/W+PEGASUS+PLUS.png" alt="Stiletto Heels" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Trendy",
        description: "Elegant stiletto heels for party wear."
    },
    {
        id: 11,
        name: "Cross Training Shoes",
        category: "sports",
        price: 3599,
        originalPrice: 4599,
        discount: 22,
        rating: 4.5,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8f3d7cf8-9a8d-41cf-b7c9-9aa6622c5612/W+AIR+ZOOM+PEGASUS+41.png" alt="Cross Training" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Fitness",
        description: "Versatile training shoes for various workouts."
    },
    {
        id: 12,
        name: "Kids Canvas Shoes",
        category: "kids",
        price: 999,
        originalPrice: 1499,
        discount: 33,
        rating: 4.3,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7cfb72aa-d7cd-4472-99ad-e4a1ea1ba31b/W+NIKE+AIR+PEGASUS+2005.png" alt="Kids Canvas" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Fun",
        description: "Lightweight canvas shoes for everyday wear."
    },
    {
        id: 13,
        name: "Leather Boots",
        category: "men",
        price: 4299,
        originalPrice: 5499,
        discount: 22,
        rating: 4.7,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/39d9ed80-48bd-4e4e-abab-93a7bbc8cb6f/W+PEGASUS+TRAIL+5+GTX.png" alt="Leather Boots" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Winter",
        description: "Stylish leather boots for winter season."
    },
    {
        id: 14,
        name: "Ballet Flats",
        category: "women",
        price: 1799,
        originalPrice: 2499,
        discount: 28,
        rating: 4.2,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/2a9bd202-0260-46cd-8dfc-4e695bd92264/PEGASUS+PLUS.png" alt="Ballet Flats" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Comfort",
        description: "Comfortable ballet flats for daily wear."
    },
    {
        id: 15,
        name: "Tennis Shoes",
        category: "sports",
        price: 2999,
        originalPrice: 3999,
        discount: 25,
        rating: 4.6,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9798729c-7ad1-4386-aeb3-8f14f9f9eb81/NIKE+AIR+PEGASUS+WAVE.png" alt="Tennis Shoes" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Sport",
        description: "Professional tennis shoes with excellent support."
    },
    {
        id: 16,
        name: "Kids Sandals",
        category: "kids",
        price: 899,
        originalPrice: 1299,
        discount: 31,
        rating: 4.5,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/2c6ba900-2a8c-48de-b7bb-b14c6cbd7ea4/W+NIKE+AIR+PEGASUS+2005.png" alt="Kids Sandals" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Summer",
        description: "Comfortable sandals for kids in summer."
    },
    {
        id: 17,
        name: "Monk Strap Shoes",
        category: "men",
        price: 3199,
        originalPrice: 4199,
        discount: 24,
        rating: 4.4,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ad4354e6-f35e-4ea7-89e3-17e154b6fa65/REACTX+PEGASUS+TRAIL+5+GTX+SP.png" alt="Monk Strap" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Classy",
        description: "Classic monk strap shoes for formal wear."
    },
    {
        id: 18,
        name: "Wedge Sandals",
        category: "women",
        price: 2199,
        originalPrice: 2999,
        discount: 27,
        rating: 4.3,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/cf4adba1-a532-43c3-a27d-e10ac170dd3d/NIKE+P-6000+PRM.png" alt="Wedge Sandals" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Casual",
        description: "Stylish wedge sandals for casual outings."
    },
    {
        id: 19,
        name: "Trail Running Shoes",
        category: "sports",
        price: 4499,
        originalPrice: 5999,
        discount: 25,
        rating: 4.8,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/45d92209-54b0-479e-b704-5ba7e752d006/W+NIKE+P-6000+GLD.png" alt="Trail Running" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Adventure",
        description: "Durable trail running shoes for outdoor adventures."
    },
    {
        id: 20,
        name: "Kids Light-Up Shoes",
        category: "kids",
        price: 1499,
        originalPrice: 1999,
        discount: 25,
        rating: 4.7,
        image: '<img src="https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/af594090-a92d-43d5-a786-3cced3538c6f/NIKE+P-6000.png" alt="Kids Light-Up" style="width: 200px; height: 200px; object-fit: contain;">',
        badge: "Light-Up",
        description: "Fun light-up shoes that kids love."
    }
];
